# importing modules

In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error


# loading data

In [28]:
# Load data
data = pd.read_csv('thermoData.csv')

XGBoost Model for Column 5
  - RMSE (Train): 25.74
  - RMSE (Test): 30.08

XGBoost Model for Column 6
  - RMSE (Train): 12.65
  - RMSE (Test): 19.58



In [65]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

# Load data
data = pd.read_csv('thermoData.csv')

# Function to train and evaluate an XGBoost model
def train_xgboost(fit_what):
    y = np.array(data.iloc[:, fit_what])  # Select target column
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)
    
    # Define XGBoost model
    model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3)
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Predictions
    predictions_test = model.predict(X_test)
    predictions_train = model.predict(X_train)
    
    # Calculate RMSE
    rmse_test = np.sqrt(mean_squared_error(y_test, predictions_test))
    rmse_train = np.sqrt(mean_squared_error(y_train, predictions_train))
    
    # Print results
    print(f'XGBoost Model for Column {fit_what}')
    print(f'  - RMSE (Train): {rmse_train:.2f}')
    print(f'  - RMSE (Test): {rmse_test:.2f}\n')
    
    return model

# Train XGBoost for column 5 and 6
model_beta = train_xgboost(5)
model_solidus = train_xgboost(6)

def generate_quaternary_compositions(steps):
    """
    Generate a grid of quaternary compositions with specified steps between points.
    Ensures that the sum of each row is always 1.0.
    
    Parameters:
        steps (int): Number of step divisions along each axis.

    Returns:
        np.array: A (n,4) array where each row sums to 1.
    """
    compositions = []
    for i in range(steps + 1):
        for j in range(steps + 1 - i):
            for k in range(steps + 1 - i - j):
                l = steps - i - j - k  # Ensure sum is 1.0
                A = i / steps
                B = j / steps
                C = k / steps
                D = l / steps
                compositions.append([A, B, C, D])

    return np.array(compositions)*100

# Example usage
steps = 100  # Defines the resolution
quaternary_compositions = generate_quaternary_compositions(steps)

# Display results
#print(quaternary_compositions[:])  # Show first 10 compositions
print("Shape:", quaternary_compositions.shape)  # Should be (N,4)
#print("Row sums:", quaternary_compositions.sum(axis=1))  # Should all be 1.0


solidus=model_solidus.predict(quaternary_compositions)

beta=model_beta.predict(quaternary_compositions)

print(solidus,beta)


XGBoost Model for Column 5
  - RMSE (Train): 25.74
  - RMSE (Test): 30.08

XGBoost Model for Column 6
  - RMSE (Train): 12.65
  - RMSE (Test): 19.58

Shape: (176851, 4)
[3083.0735 3083.0735 3083.0735 ... 1961.9154 1961.9154 1961.9154] [ 656.8539  656.8539  656.8539 ... 1293.2653 1293.2653 1293.2653]


[2084.7197 2084.7197 2084.7197 ... 2084.7197 2084.7197 2084.7197] [850.4621 850.4621 850.4621 ... 850.4621 850.4621 850.4621]


In [ ]:
tstep=0
solidus_threshold = 2200-tstep
beta_threshold = 806+tstep
filtered_data=[]
for i,val in enumerate(quaternary_compositions):
    if(solidus[i]>solidus_threshold and beta[i]<beta_threshold and val[0] >= 5 and val [1] >= 5 and val[2] >= 5 and val[3]>=5):
        filtered_data.append([val[0],val[1],val[2],val[3],beta[i],solidus[i]])
filtered_data=np.array(filtered_data)
print(len(filtered_data))
print(filtered_data)


1
[[   5.           20.           20.           55.          783.64752197
  2217.86914062]]


In [86]:
print(np.max(solidus),np.min(beta))

3092.389 511.4256


In [58]:
print(solidus)

[2070.4866 2070.4866 2070.4866 ... 2070.4866 2070.4866 2070.4866]


In [60]:
print(quaternary_compositions[0])

[0. 0. 0. 1.]
